openapi: "3.0.3"
info:
  title: Reusable components for CloudEvents
  description: The definitions comply with the [JSON format](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md) of the [CloudEvents 1.0 specification](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md).
  version: "${project.version}"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths: {}
components:
  schemas:
    AsynchronousMessageBase: # extend this schema with allOf to define schemas for specific events, with constraints on data/data_base64 and type
      type: object
      description: Context attributes of an AsynchronousMessage in CloudEvent JSON format.
      # An AsynchronousMessage is an extension of the CloudEvent format, also allowing other async exchanges than events.
      properties:
        specversion:
          type: string
          minLength: 1
          description: The version of the CloudEvents specification used to represent the message.
          example: "1.0"
        id:
          type: string
          minLength: 1
          description: Identifies the message. Producers MUST ensure that source + id is unique for each distinct message. If a duplicate message is re-sent (e.g. due to a network error) it MAY have the same id. Consumers MAY assume that Asynchronous Messages with identical source and id are duplicates.
          example: "550e8400-e29b-41d4-a716-446655440000"
        type:
          description: >
            Type of the message.<br>
            Often this attribute is used for routing, observability, policy enforcement, etc. 
            The format of this is producer defined and might include information such as the version of the type.<br>

            The type SHOULD be prefixed with a reverse-DNS name. The prefixed domain dictates the organization which defines the semantics of this message type.
          type: string
          minLength: 1
          example: "be.belgif.example.meeting.v3.meetings.create"
        service:
          description: |
            Name of the service (API) that defines the format and exchange protocol of this message.
            Recommended to use reverse DNS notation, with the last segment being the major version number prefixed by the letter `v`.
          type: string
          minLength: 1
          example: "be.belgif.example.meeting.v3"
        source:
          type: string
          format: uri-reference
          minLength: 1
          description: >
            Identifies the context in which the message was created.<br>
            Often this will include information such as the type of the message source, the organization publishing the message or the process that produced the message. The exact syntax and semantics behind the data encoded in the URI is defined by the message producer.<br>

            Producers MUST ensure that source + id is unique for each distinct message.<br>

            An application MAY assign a unique source to each distinct producer, which makes it
            easy to produce unique IDs since no other producer will have the same source.
            The application MAY use UUIDs, URNs, DNS authorities or an application-specific
            scheme to create unique source identifiers.<br>

            An absolute URI is RECOMMENDED
          example: "urn:async-source:client:123"
        datacontenttype:
          type: string
          minLength: 1
          description: Media type of the payload (values of data or data_base64).
            MUST adhere to the format specified in RFC 2046.
          default: "application/json"
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
        subject:
          type: string
          minLength: 1
          description: Subject of the message (optional, may also be only present in payload)
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
        time:
          type: string
          format: date-time
          description: Timestamp of when the occurrence happened. If the time of the occurrence cannot be determined then this attribute MAY be set to some other time (such as the current time) by the CloudEvents producer, however all producers for the same source MUST be consistent in this respect. In other words, either they all use the actual time of the occurrence or they all use the same algorithm to determine the value used.
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
        dataschema:
          description: Identifies the schema that data adheres to. Incompatible changes to the schema SHOULD be reflected by a different URI.
          type: string
          minLength: 1
          nullable: true
          format: uri
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
      required: [ id, type, service, specversion, source ]
      example:
        {
          "specversion": "1.0",
          "id": "550e8400-e29b-41d4-a716-446655440000",
          "service": "be.belgif.example.meeting.v3",
          "type": "be.belgif.example.meeting.v3.meetings.create",
          "source": "urn:async-source:client:123",
          "subject": "132456",
          "data": { "...": "..." }
        }

    AsynchronousMessage:
      description: An asynchronous message represented using the [CloudEvents standard](https://github.com/cloudevents/spec).
        An asynchronous message is a message exchanged between parties without requiring simultaneous presence.
        An asynchronous message may be extended with additional context attributes, which should follow the naming and typing constraints specified by the [CloudEvents specification](https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#context-attributes).
      allOf:
      - $ref: "#/components/schemas/AsynchronousMessageBase"
      type: object
      properties:
        data:
          description: The message payload in JSON format
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
        data_base64:
          description: Base64 encoded message payload. Must adhere to RFC4648. This property is mutually exclusive with `data`.
          type: string
          format: byte
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
          example: "Zm9vYg=="
        relatedto:
          description: The id of the request message for which this message is a reply. Must be present for reply or problemReply messages
          type: string
          minLength: 1
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
        relatedtosource:
          description: The `source` of the message for which this message is a reply. This attribute MUST be present when `relatedTo` is present.
          type: string
          minLength: 1
          nullable: true
          x-ignore-rules:
            jsn-null: allow null to comply with CloudEvents 1.0 spec
      additionalProperties: true
        # restrictions on additional properties are commented out because they don't work well for code generation
        # additional context attributes:
        #       MUST consist of lower-case letters [a-z] or digits [0-9] from the ASCII character set.
        #       SHOULD start with a letter.
        #       MUST be at least one character in length, and SHOULD NOT exceed 20 characters.
        #       SHOULD be descriptive and terse.
        # The CloudEvents specification only supports below types for context attributes, to maximize messaging protocol compatibility
        # See https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#type-system and https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md#22-type-system-mapping
#        oneOf:
#          - type: string  # includes attributes with base64-encoded, uri, uri-reference or timestamp types
#            nullable: true
#            x-ignore-rules:
#              jsn-null: allow null to comply with CloudEvents 1.0 spec
#          - type: integer
#            format: int32
#            nullable: true
#            x-ignore-rules:
#              jsn-null: allow null to comply with CloudEvents 1.0 spec
#          - type: boolean
#            nullable: true
#            x-ignore-rules:
#              jsn-null: allow null to comply with CloudEvents 1.0 spec
      x-ignore-rules:
        jsn-naming: allow underscore in data_base64 property in order to comply with the CloudEvents standard

    AsynchronousReplyMessageBase:
      description: Context attributes for reply messages
      type: object
      allOf:
        - $ref: "#/components/schemas/AsynchronousMessageBase"
        - properties:
            relatedto:
              description: The `id` of the corresponding request message
              type: string
              minLength: 1
            relatedtosource:
              description: The `source` of the corresponding request message
              type: string
              minLength: 1
          required: [relatedto, relatedtosource]
      example:
        {
          "specversion": "1.0",
          "id": "123ef800-e29b-41d4-a716-546655440001",
          "service": "be.belgif.example.meeting.v3",
          "source": "urn:async-source:be.belgif.example",
          "type": "be.belgif.example.meeting.v3.meetings.create.reply",
          "relatedto": "550e8400-e29b-41d4-a716-446655440000",
          "relatedtosource": "urn:async-source:client:123",
          "subject": "132456",
          "data": { "...": "..." }
        }

    AsynchronousProblemReplyMessage:
      description: An asynchronous problem reply message
      type: object
      allOf:
        - $ref: "#/components/schemas/AsynchronousReplyMessageBase"
        - properties:
            data:
              $ref: "../../problem/v1/problem-v1.yaml#/components/schemas/Problem"
          required: [data]
      example:
        {
          "specversion": "1.0",
          "id": "987654-1234-1235-4567489798",
          "service": "be.belgif.example.meeting.v3",
          "source": "urn:async-source:be.belgif.example",
          "type": "be.belgif.example.meeting.v3.meetings.create.problemReply",
          "datacontenttype": "application/problem+json",
          "relatedto": "550e8400-e29b-41d4-a716-446655440000",
          "relatedtosource": "urn:async-source:client:123",
          "data": {
            "type": "urn:problem-type:belgif:badRequest",
            "href": "https://www.belgif.be/specification/rest/api-guide/problems/badRequest.html",
            "title": "Bad Request",
            "detail":  "The input message is incorrect",
            "instance": "urn:uuid:987654-1234-1235-4567489798",
            "issues": [
              {
                "type": "urn:problem-type:belgif:input-validation:schemaViolation",
                "detail": "value 123 of invitees[0] is not of type string",
                "in": "body",
                "name": "invitees[0]",
                "value": 123
              }
            ]
          }
        }
